### ISSUE TITLE
Does LinkedList expose the head node directly?

### ISSUE THREAD

**Issue by mikehaas763** [mauriciosantos/Buckets-JS#12]
All of the methods I see in the documentation return the element from the underlying array. This makes it impossible to do something like `node.next` to walk the linked list. I looked at the source for a minute, am I missing something?

**Comment by mauriciosantos** [comment]
you can't access the list nodes directly, but you can iterate through the list elements using  the forEach method.

**Comment by mikehaas763** [comment]
I see, thanks for the info. If you can't get access to the underlying nodes then quite frankly LinkedList is not a linked list. It's simply a glorified array.
